name: Docker Image CHR
on:
  push:
    branches: [ "main" ]
jobs:
  test-tunnel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: mencari id
        id: test
        run: echo "::set-output name=mix::1"
      - run:  npm install -g selenium-side-runner
      - name: v1
        if: steps.test.outputs.mix == 1
        run: selenium-side-runner -w 4 "yttest.side" --server https://mooghenchris:oi5z2Pw85yJEv1F5FkYNi9CqYkTHs7l6WLjsVnp4xFZOtmRQWR@hub.lambdatest.com/wd/hub -c "browserName='chrome' version='72.0' platform='Windows 10' resolution='1024x768'"
      - run: |
         echo "`cat README.md` > 
         - `date` success >
         " > README.md 
         git config --global user.name 'mooghen'
         git config --global user.email 'mooghenchris@proton.me'
         git commit -am "Automated report succes"
         git push
      - name: Automated report succes
        if: ${{ failure() }}
        run: |
         echo "`cat README.md` > 
         - `date` failure >
         " > README.md 
         git config --global user.name 'mooghen'
         git config --global user.email 'mooghenchris@proton.me'
         git commit -am "Automated report failure"
         git push
