name: Docker Image CHR
on:
  schedule:
    - cron: '*/12 * * * *'
jobs:
  test-tunnel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - name: mencari id
        id: test
        run: echo "::set-output name=mix::`echo $((1 + $RANDOM % 3))`"
      - run: echo v${{ steps.test.outputs.mix }}
      - run: |
         echo "`cat README.md` > 
         - `date` success v${{ steps.test.outputs.mix }} >
         " > README.md 
         git add -A
         git config --global user.name 'mooghen'
         git config --global user.email 'mooghenchris@proton.me'
         git commit -m "[deploy: production]" 
         git push
      - name: Automated report succes
        if: ${{ failure() }}
        run: |
         echo "`cat README.md`  > 
         - `date` failure v${{ steps.test.outputs.mix }} >
         " > README.md 
         git config --global user.name 'mooghen'
         git config --global user.email 'mooghenchris@proton.me'
         git commit -m "[deploy: production]"
         git push
