# oi5z2Pw85yJEv1F5FkYNi9CqYkTHs7l6WLjsVnp4xFZOtmRQWR
name: Docker Image CHR
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/12 * * * *'
jobs:
  test-tunnel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: mencari id
        id: test
        run: echo "::set-output name=mix::`echo $((1 + $RANDOM % 7))`"
      - run: echo v${{ steps.test.outputs.mix }}
      - run:  npm install -g selenium-side-runner
      - name: v${{ steps.test.outputs.mix }}
        if: ${{ steps.test.outputs.mix }}
        run: selenium-side-runner -w 4 "yttest${{ steps.test.outputs.mix }}.side" --server https://mooghenchris:${{ secrets.LMD }}@hub.lambdatest.com/wd/hub -c "browserName='chrome' version='72.0' platform='Windows 10' resolution='1024x768'"
      - run: |
         echo "`cat README.md` > 
         - `date` success v${{ steps.test.outputs.mix }} >
         " > README.md 
         
         git add . 
         git config --global user.name 'mooghen'
         git config --global user.email 'mooghenchris@proton.me'
         git commit -am "Automated report succes test v${{ steps.test.outputs.mix }}"
         git push
      - name: Automated report succes
        if: ${{ failure() }}
        run: |
         git add . 
         echo "`cat README.md`  > 
         - `date` failure v${{ steps.test.outputs.mix }} >
         " > README.md 
         git config --global user.name 'mooghen'
         git config --global user.email 'mooghenchris@proton.me'
         git commit -am "Automated report failure test v${{ steps.test.outputs.mix }}"
         git push
